//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wine_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class wineSetEntities : DbContext
    {
        public wineSetEntities()
            : base("name=wineSetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<winequalityRed> winequalityRed { get; set; }
    
        public virtual ObjectResult<winequalityRed> asp_Podaci_Za_Treniranje_KNN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<winequalityRed>("asp_Podaci_Za_Treniranje_KNN");
        }
    
        public virtual ObjectResult<winequalityRed> asp_Podaci_Za_Treniranje_KNN(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<winequalityRed>("asp_Podaci_Za_Treniranje_KNN", mergeOption);
        }
    
        public virtual ObjectResult<winequalityRed> asp_Trening_Podaci_Za_KNN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<winequalityRed>("asp_Trening_Podaci_Za_KNN");
        }
    
        public virtual ObjectResult<winequalityRed> asp_Trening_Podaci_Za_KNN(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<winequalityRed>("asp_Trening_Podaci_Za_KNN", mergeOption);
        }
    }
}
