//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wine_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class winequalityRed
    {
        public int ID { get; set; }
        public string fixed_acidity { get; set; }
        public string volatile_acidity { get; set; }
        public string citric_acid { get; set; }
        public string residual_sugar { get; set; }
        public string chlorides { get; set; }
        public string free_sulfur_dioxide { get; set; }
        public string total_sulfur_dioxide { get; set; }
        public string density { get; set; }
        public string pH { get; set; }
        public string sulphates { get; set; }
        public string alcohol { get; set; }
        public string quality { get; set; }
    }
}
